env:
  es2021: true
  node: true
  jest: true
extends:
  - "eslint:recommended"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "jest"
rules:
  no-var:
    - error
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  camelcase:
    - error
  no-unused-vars:
    - off
